### ISSUE TITLE
Collect new features / improvements ideas for academia & researchers

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#171]
TODO @ivokub

**Comment by ivokub** [comment]
These papers are using either gnark or gnark-crypto:
* https://eprint.iacr.org/2021/100.pdf
* https://eprint.iacr.org/2021/1443.pdf

- [ ] add a bibtex citation reference to gnark so that we could better track the uses using Google Scholar alerts
- [ ] add a bibtex citation reference to gnark-crypto
- [ ] list references in README/gnark-doc
- [ ] add API which allows to measure the cost of the circuits (e.g. # of scalar muls/adds/multiexps, pairings, ecc adds etc.)
- [ ] add an example how to swap the curves
- [ ] get feedback from the researchers using gnark

**Comment by gbotrel** [comment]
I did the Zenodo integration. Next releases of gnark and gnark-crypto will add the bibtex + zenodo DOI badge.
