### ISSUE TITLE
perf: merging constraints in plonk

### ISSUE THREAD

**Issue by ThomasPiellard** [ConsenSys/gnark#243]
In plonk, when one creates a new variable like this for instance
`z := api.Add(api.Mul(x,y), 4)`
2 constraints are created, even if the intermediate result `api.Mul(x,y)` is not reused.

**Comment by gbotrel** [comment]
I have an idea, which will be I think efficient to implement. (it accidentally solves #242 ). 

For a R1CS, idea is when you add a new constraint, if it’s in the form 1 * X == Y,  then, you always replace X by its original expression . 
2 cases:
1. a * b == X 
2. X * a == b 


1. we end up with a * b == Y 
2. we end up with Y * a == b

You keep a map of “orphans” constraints (ie a “new internal wire” is created, you add it to the map. When it’s referenced in any subsequent constraint, you remove it from the map. 

In a post compile phase, you delete all orphans and shift the ids accordingly (yet to figure out how to do that efficiently).

This approach make more sense for the Plonkish cs, since it avoids recursively “packing” linear/quadratic constraint into one. Currently with our api, if you write
y = x*x
-3y + yx + 2x == 0

it is going to create 4 constraints;
1. y = x *x
2. y * x = z
3. 2x - 3y = a
4. a + z == 0

with this proposition, it would be
1. y = x*x
2. y * x = z —> orphan
3. 2x - 3y = a —> orphan
4. 2x - 3y + y*x = 0

The idea is similar to R1CS, except, our API mostly creates either “linear” or “quadratic” plonkish constraints now. 

Note that since the parallel solver PR, we build a map of wire -> constraint (ie which constraint solved which wire) at post compile phase, and this data structure may be useful sooner 👍 .

**Comment by gbotrel** [comment]
closing, superseded by plonk+custom gates wip.
