### ISSUE TITLE
How to add constraints into R1CS struct directly

### ISSUE THREAD

**Issue by LBruyne** [ConsenSys/gnark#397]
I'm doing a work parsing .r1cs file into gnark system, more formally, adding a feature so that gnark can prove and verify a .r1cs file compiled by circom (details in https://github.com/iden3/r1csfile/blob/master/doc/r1cs_bin_format.md)
A necessary thing to do is adding constraints(arrays of L,R,O) into R1CS or CCS struct. But I only find a addConstraint (the figure following) method which is an inner method of R1CS struct. 
![image](https://user-images.githubusercontent.com/46318701/201864587-40629378-d998-4ccb-bc8b-031aefb173b4.png)
So why not add a interface method to API interface so that we can add constraints flexibly?
![image](https://user-images.githubusercontent.com/46318701/201865504-bae6ca6e-9a87-4628-8886-95e4af15bfbf.png)

**Comment by ivokub** [comment]
Hi @LBruyne, good question. We have actually thought about it a little, but the main problem is that we support right now both R1CS and sparse R1CS (or PLONK), but they have different types of gates (R1CS has LR=O and sparse R1CS has aL+bR+cLR=dO. But in R1CS L,R,O may be linear combinations of variables, where in sparse R1CS they are variables). If in the future we may support TurboPLONK style custom gates, then adding a constraint directly would require another different interface. If we want to expose the method in `frontend.API`, it has to support different constraint systems nicely.

So, it isn't that straightforward, but maybe there is an option to add something like `AddMul(left, right, toAdd, res)` which would record `left*right+toAdd = res`.

**Comment by LBruyne** [comment]
I see, but as you know, a constraint in the .r1cs file is processed nicely in a format: (L, R, O), so i want to add it into the R1CS struct directly (such as add a new LRO tuple) but there is not a direct way (a public method), what should i do with this?

**Comment by ivokub** [comment]
> @ivokub I see, but as you know, a constraint in the .r1cs file is processed nicely in a format: (L, R, O), so i want to add it into the R1CS struct directly (such as add a new LRO tuple) but there is not a direct way (a public method), what should i do with this?
> 
> > Hi @LBruyne, good question. We have actually thought about it a little, but the main problem is that we support right now both R1CS and sparse R1CS (or PLONK), but they have different types of gates (R1CS has LR=O and sparse R1CS has aL+bR+cLR=dO. But in R1CS L,R,O may be linear combinations of variables, where in sparse R1CS they are variables). If in the future we may support TurboPLONK style custom gates, then adding a constraint directly would require another different interface. If we want to expose the method in `frontend.API`, it has to support different constraint systems nicely.
> > So, it isn't that straightforward, but maybe there is an option to add something like `AddMul(left, right, toAdd, res)` which would record `left*right+toAdd = res`.

Sorry for the delay. I think right now there isn't a nice way of doing it. I think one option would be to have a local patch on top of gnark which would allow it (essentially making the method for adding individual constraints in R1CS public). If we would add it into gnark directly, then users would start to depend on this functionality, but in the future we would definitely want to change the signature of these methods (with the introduction of custom gates etc.).

However, I think, your actual problem is slightly different -- would it be useful if there is some kind of transpiler from circom format to gnark binary format for circuits? There are different representations out there (VampIR, circom, xjsnark, Noir etc.) and we have been thinking about having a way to transpile these formats into gnark format for comparison / compatibility. For example, circom ecosystem has a wide range of different circuits and it would be great if it would be possible to use these circuits in gnark (for proving/verifying).

**Comment by LBruyne** [comment]
Thank you for your answer!

**Comment by ivokub** [comment]
> @ivokub Thank you for your answer!

@LBruyne - can you have a look if https://github.com/ConsenSys/gnark/pull/452 would solve your use case?

**Comment by LBruyne** [comment]
@ivokub Pretty well! I've read the demo it list in the PR. It seems very convenient to use.
I believe the only thing left to do is parsing the .r1cs file produced by circom and adding the constraints using this API. But 
 I think this could be done personally if you think it's uncomfortable to add such a interface.
This issue seems to be closed.
Thanks for the work again!
