### ISSUE TITLE
GKR as API

### ISSUE THREAD

**Issue by Tabaie** [Consensys/gnark#425]
It would be nice for the user to construct GKR circuits the same way as they construct SNARKs. To make that as seamless as possible, I propose GKR API objects that work more or less the same as regular APIs, with an extra bit of setup and takedown.
The following is an example of a circuit that computes `x, y -> x^2 + y`:
```go
type xSqPlusYCircuit struct {
	X, Y []frontend.Variable
}

func (c *xSqPlusYCircuit) Define(api frontend.API) error {
	_gkr := gkr.NewApi()
	var x, y frontend.Variable
	var err error
	if x, err = _gkr.Input(c.X); err != nil {
		return err
	}
	if y, err = _gkr.Input(c.Y); err != nil {
		return err
	}
	t := _gkr.Mul(x, x)
	_gkr.Add(y, t)
	var gkrOuts [][]frontend.Variable
	if gkrOuts, err = _gkr.Output(api); err != nil {
		return err
	}
	Z := gkrOuts[0]

	for i := range c.X {
		api.AssertIsEqual(Z[i], api.Add(api.Mul(c.X[i], c.X[i]), c.Y[i]))
	}
	return nil
}
```

The following functions are introduced:
1. `NewApi()`: Creates a new GKR API, not much to it.
2. `Input([]frontend.Variable)`: (`Import`?) Creates a GKR input variable with the slice being its values across all instances.
3. `Output(frontend.API)`: (`Compile`? `Export`?) Compiles and finalizes the GKR circuit and spits out assignments (`[]frontend.Variable`) for the output variables in the order created. That is why the output variable resulting from `_gkr.Add(y, t)` is not captured in that line.
4. `Mul`: is the part that's supposed to resemble a regular API. Except that the user has no need to capture the result in case of an output variable, instead getting its assignments from the `Output` function.

### Remarks
* Not all functionalities of an API are actually implemented by `gkr.API`, only those directly used for constructing circuits. For example, writing `_gkr.Compiler()` would result in a panic.
* It may be desirable to do away with the `Input` and `Output` functions and treat slices of `frontend.Variable` as GKR variables. I see three potential difficulties with this: 
     1. For the user to have access to all of the GKR circuit's internal variables, a hint should be run for each variable which may incur a performance penalty.
     2. Consider a case where we are proving correctness of a Merkle tree root. Then, the GKR circuit would consist of a hash `H(x_i, x'_i)=y_i` and 2^d instances of it for a tree of depth d. However, due to the Merkle tree's structure there are value dependencies between inputs and outputs across different instances such as `x'_3 = y_2`. It is unreasonable to expect the user to compute `y_2` independently just so that they can provide the input value `x'_3` when defining the input wire `x'`. (An interface for marking these dependencies will be outlined later.)
     3. It may get a bit messy trying to use slices as map keys.
* Under the hood, the `Output` method also computes the GKR proof and encodes a GKR verifier.

**Comment by ivokub** [comment]
It looks to be somewhat similar to how I had implemented field emulation. For that I have the [Field](https://pkg.go.dev/github.com/consensys/gnark@v0.7.2-0.20221221150941-24fe00b5a092/std/math/emulated#Field) type which operates on non-native `Element` types. Because of separate types (from `frontend.Variable`), it makes implementation easier when taking as inputs `frontend.Variable`, which I would have to type assert in methods. There is also [FieldAPI](https://pkg.go.dev/github.com/consensys/gnark@v0.7.2-0.20221221150941-24fe00b5a092/std/math/emulated#FieldAPI) type which implements `frontend.API`, but it is a bit messy and was quite time-consuming to implement all API methods. But it allows to take an existing circuit (working with frontend.Variables) and run it over any non-native fields.

I think implementing whole `frontend.API` for the GKR API is very time-consuming and doesn't make too much sense in GKR context.

Just trying to throw some ideas, maybe something like this (assume that inputs are at layer 0 and outputs at d):
```
type Variable struct { /*position*/ } // separate from frontend.Variable

type GKR interface { // doesn't have to be interface if we actually have a single implementing instance
    // NewVariable takes circuit variable and returns GKR variable in layer 0 and correct position. Panics when called after Commit()
    NewVariable(frontend.Variable) *Variable

    // Add adds two variables and returns a new variable at layer max(a.layer, b.layer) + 1. Panics when called after Commit()
    Add(a, b *Variable) *Variable
    // Mul multiplies two variables and returns a new variable at layer max(a.layer, b.layer) + 1. Panics when called after Commit()
    Mul(a, b *Variable) *Variable
    // Maybe other relevant methods i.e. XOR, etc. if GKR prover also supports custom gates.

    // Output takes a GKR variable, computes its value and returns computed frontend.Variable. If same variable is output several times then use cache. Panics when called after Commit()
    Output(a *Variable) frontend.Variable

    // Commit finalises the GKR circuit. Computes the GKR proof and verifies GKR proof in-circuit. Usually we would defer it after NewGKR.
    Commit()
}

func NewGKR(api frontend.API) (GKR, error) // returns new GKR object to work with. If GKR is type not interface then return pointer so that can pass safely around if GKR has mutating state
```

Now, the usage in circuit would be something like this:
```go
type Circuit struct {
    InputA, InputB frontend.Variable
}

func (c *Circuit) Define(api frontend.API) error {
    gkr, err := NewGKR(api)
    if err != nil {
        return fmt.Errorf("init GKR: %w", err)
    }
    defer gkr.Commit()
    x := gkr.NewVariable(c.InputA)
    y := gkr.NewVariable(c.InputB)
    xx := gkr.Mul(x, x)
    yy := gkr.Mul(y, y)
    xxyy := gkr.Mul(xx, yy)
    res := gkr.Output(xxyy)
    nativeRes := api.Mul(api.Mul(c.X, c.X), api.Mul(c.Y, c.Y))
    api.AssertIsEqual(res, nativeRes)
    return nil
}
```

**Comment by ivokub** [comment]
Independently, for long-term plan, maybe it would also good to refactor `frontend.API` such that arithmetic operations would be in a separate interface so that we could use existing gadgets (for example, to compute hash) either with native API or GKR API. This would allow to use either native API or GKR API to compute hashes using gadgets in `std/` etc, but this would require Go generics, which are not too usable yet.

**Comment by gbotrel** [comment]
@ivokub isn't `Commit` playing a duplicate role with `Output`?

Some random ideas; would it be possible to do without the `Output` function?
The syntax; 
```go
xx := gkr.Mul(x, x)
xxy := gkr.Add(xx, y)
res := gkr.Output(xxy)
```
is a bit weird to my uneducated eyes; because I can capture the output of `gkr.Mul` and re-use it, but can't do so for `Add` without going through `Output`. 

So what if the object returned by `gkr` APIs is a stateful lambda; so you could do something like;
```go
xx := gkr.Mul(x, x)
xxy := gkr.Add(xx, y)
gkr.Compile() // Finalize // Commit or whatever

// later
xxy(i) // returns frontend.Variable
or xxy.At(..) // if we need an object that's reusable in gkr api?
```

Again, maybe I misunderstood how to use the output.

2 other cosmetics remarks; 
I prefer: 
```
gkr := gkr.New(api) 
to 
gkr := gkr.NewGKR(api)
```
and subsequent calls on the `gkr` object (like `Output` or `Compile` shouldn't take an `api` object again in params. 

Semantically, `gkr.Input` (so maybe `gkr.NewInput`) does separate things better from my perspective; having a `gkr.Variable` that behaves quite differently than a `frontend.Variable` seems a bit odd but not strongly opinionated here.

**Comment by ivokub** [comment]
> @ivokub isn't `Commit` playing a duplicate role with `Output`?
> 
> Some random ideas; would it be possible to do without the `Output` function? The syntax;
> 
> ```go
> xx := gkr.Mul(x, x)
> xxy := gkr.Add(xx, y)
> res := gkr.Output(xxy)
> ```
> 
> is a bit weird to my uneducated eyes; because I can capture the output of `gkr.Mul` and re-use it, but can't do so for `Add` without going through `Output`.

So, how I have understood how GKR works is that the GKR variables are essentially location pointers within the GKR circuit (compared to R1CS/PLONK variables, which are linear expressions or pure terms). The method `Output()` takes in this GKR variable and returns the computed frontend variable array (not sure, but I think this can be computed using hint). 

The GKR stuff works in essence that the API constructs first the GKR circuit, then it is proved with GKR prover in gnark-crypto and the GKR proof is verified in-circuit. The proposed method `Commit()` builds GKR circuit proof and embeds its verification circuit in R1CS/PLONK.

Imo they were different enough operations that is good to have different methods. Maybe it makes more sense if `Input`, `Output` have more descriptive names a la `FromVariable` and `ToVariable`. I also think for the end-user it is a lot better if the GKR variables and frontend variables are different types so that they couldn't be accidentally used in other context (well, it is still possible to provide GKR variable as an input to frontend.API methods, but this will most probably panic).

> 
> So what if the object returned by `gkr` APIs is a stateful lambda; so you could do something like;
> 
> ```go
> xx := gkr.Mul(x, x)
> xxy := gkr.Add(xx, y)
> gkr.Compile() // Finalize // Commit or whatever
> 
> // later
> xxy(i) // returns frontend.Variable
> or xxy.At(..) // if we need an object that's reusable in gkr api?
> ```

I understood that GKR variable can represent a many variables at a time (a la Single-Instruction-Multiple-Data in GPU contexts), so there wouldn't be a need to access individual values within GKR circuit.

**Comment by ivokub** [comment]
> @ivokub isn't `Commit` playing a duplicate role with `Output`?

Oh, forgot to add. I think it would be still nice to have some kind of post-compile hook which `gkr.New` uses to attach `Commit()`. Then it wouldn't be necessary to expose this method at all for the users and it would be invoked automatically. So the users wouldn't have to figure out where to call the method which actually computes GKR proof and embeds the verifier in gnark circuit.
