### ISSUE TITLE
Is it possible to define a circuit at runtime (using a map, etc)?

### ISSUE THREAD

**Issue by semaj** [ConsenSys/gnark#47]
Hello, and thank you for your work!
I am trying to define circuit variables at runtime, rather than at compile time using a struct. For instance, I'd like to do something like 
```go
type CubicCircuit struct {
	Inner map[string]frontend.Variable
}
...
func (circuit *CubicCircuit) Define(curveID gurvy.ID, cs *frontend.ConstraintSystem) error {
	x3 := cs.Mul(circuit.Inner["X"], circuit.Inner["X"], circuit.Inner["X"])
	cs.AssertIsEqual(circuit.Inner["Y"], x3)
	return nil
}


```
Rather than 
```go
type CubicCircuit struct {
	X frontend.Variable `gnark:"x"`
	Y frontend.Variable `gnark:"y"`
}
...
func (circuit *CubicCircuit) Define(curveID gurvy.ID, cs *frontend.ConstraintSystem) error {
	x3 := cs.Mul(circuit.X, circuit.X, circuit.X)
	cs.AssertIsEqual(circuit.Y, x3)
	return nil
}
```
The circuit compilation, setup, and proving steps appear to compile (in the former case), but creating a witness fails to compile as follows:
```go
solution := CubicCircuit{}
solution.Inner["X"].Assign(2) // fails to compile with Assign is not in method set of frontend.Variable
```
Is this type of thing possible at all? Thanks!

**Comment by gbotrel** [comment]
Hi,

I think I see what happens: using `map` for public or secret Variable (the witness) is not supported. You should see a warning at compile time like so: "warning: map values are not addressable, ignoring"" . 

`Inner map[string]frontend.Variable` is not parsed or recognized as witness, so in your `Define` you are manipulating circuit intermediate variables, rather than witness value. These can't be assigned. 

I don't think we will support `map` in the near future, but slices (that you need to initialize before calling `Compile`) or arrays are supported.

**Comment by semaj** [comment]
Thank you, that answers my question!
