### ISSUE TITLE
`api.Cmp` performs unsigned comparison 

### ISSUE THREAD

**Issue by aybehrouz** [ConsenSys/gnark#588]
Current documentation of `api.Cmp` says nothing about the important fact that this function performs unsigned comparison. This should be added to the documentation.

Unsigned comparison is error prone. For example, something simple like `api.Cmp(1, -1)` returns `-1` (means `1` is smaller than `-1`). I recommend having a special function like `api.CmpUnsigned` for unsigned comparison, and `api.Cmp` implementing signed comparison for numbers in range `-P/2 < x < P/2`.

**Comment by ivokub** [comment]
Hi @aybehrouz, this works as intended. The variables in-circuit are field elements. The integer values of the field elements are between [0, r-1] (where r is the modulus of the scalar field of the elliptic curve) and all inputs are modular reduced to this range. So what happens if you assign `-1` to witness is that the actual witness value is `r-1`. And then `api.Cmp(1, r-1) = -1`, as expected.

If you need to work with arbitrary integers, you could use field emulation `std/math/emulated` which also supports ring (when modulus isn't prime) arithmetic.

**Comment by aybehrouz** [comment]
In modulus arithmetic, the additive inverse of `x` is `m - x`, and we conventionally assume any `x` such that `0 < x < m/2` is positive and `m/2 <= x < m` are negative. We don't need to think that all numbers are positive. That's why I'd say you should mention in the docs that `cmp` performs unsigned comparison, which means it assumes that all numbers are positive and all `0, 1, ..., m-1` map to positive numbers. (exactly like a `uint` vs `int`)
